name: Build Qt6 C++ Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install aqtinstall
      run: python3 -m pip install --upgrade pip aqtinstall

    - name: Install Qt6
      run: |
        python3 -m aqtinstall install-qt linux desktop 6.6.0 linux-g++-64 \
          --modules qtbase qttools linguist \
          --outputdir $HOME/Qt \
          --autodesktop

    - name: Show Qt version
      run: |
        $HOME/Qt/6.6.0/gcc_64/bin/qmake --version
        $HOME/Qt/6.6.0/gcc_64/bin/lupdate --version
        $HOME/Qt/6.6.0/gcc_64/bin/lrelease --version

    - name: Update translations
      run: |
        $HOME/Qt/6.6.0/gcc_64/bin/lupdate . -recursive -ts translations/app.ts
        $HOME/Qt/6.6.0/gcc_64/bin/lrelease translations/app.ts -qm translations/app.qm

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$HOME/Qt/6.6.0/gcc_64 -DCMAKE_BUILD_TYPE=Release
        cmake --build . --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qt-build
        path: build/
