name: Build Qt6 C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ 安装 Qt6（包括 LinguistTools & X11Extras）
    - name: Setup Qt6
      uses: qt-actions/setup-qt@v2
      with:
        version: 6.6.2        # 指定 Qt6 版本
        host: linux
        modules: qtbase, linguisttools, x11extras

    # 3️⃣ 确认 Qt6 环境变量
    - name: Display Qt paths
      run: |
        echo "QT_DIR=$QT_DIR"
        echo "PATH=$PATH"

    # 4️⃣ 创建 build 目录
    - name: Create build directory
      run: mkdir -p build

    # 5️⃣ 配置 CMake
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=$QT_DIR/lib/cmake/Qt6

    # 6️⃣ 编译项目
    - name: Build Project
      run: cmake --build build --config Release --parallel

    # 7️⃣ 可选：运行单元测试（如果有）
    - name: Run tests
      run: ctest --test-dir build --output-on-failure
