name: Build Qt C++ Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QT_DIR: ${{ runner.temp }}/Qt6
      QT_VERSION: "6.5.3"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install aqtinstall
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install aqtinstall

      - name: Install Qt 6.5.3 with LinguistTools
        run: |
          python3 -m aqt install-qt linux desktop $QT_VERSION linux-g++-64 \
            --modules qtbase qttools linguisttools \
            --outputdir $QT_DIR \
            --autodesktop

      - name: Add Qt bin to PATH
        run: |
          echo "$QT_DIR/$QT_VERSION/gcc_64/bin" >> $GITHUB_PATH

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=$QT_DIR/$QT_VERSION/gcc_64/lib/cmake/Qt6

      - name: Build project
        run: cmake --build build --parallel

      - name: Update translation files (.ts → .qm)
        run: |
          if [ -d "translations" ]; then
            for tsfile in translations/*.ts; do
              lrelease "$tsfile" -qm "build/$(basename ${tsfile%.ts}.qm)"
            done
          fi

      - name: List built files
        run: ls -R build
