name: Build Qt C++ Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QT_INSTALL_DIR: /opt/Qt6
      QT_VERSION: 6.6.0
      QT_COMPONENT: qt.qt6.660.gcc_64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget perl python3

    - name: Download Qt Online Installer
      run: |
        wget https://download.qt.io/official_releases/online_installers/qt-online-installer-linux-x64-online.run -O qt-installer.run
        chmod +x qt-installer.run

    - name: Create non-interactive installation script
      run: |
        cat > qt-install-noninteractive.qs <<'EOF'
        var installer = gui.currentInstaller();
        installer.setTargetDirectory(installer.value("QT_INSTALL_DIR"));
        installer.selectComponent(installer.value("QT_COMPONENT"));
        installer.performInstallation();
        installer.autoRejectMessageBoxes();
        EOF

    - name: Install Qt6 non-interactively
      run: |
        sudo QT_INSTALL_DIR=$QT_INSTALL_DIR QT_COMPONENT=$QT_COMPONENT ./qt-installer.run --script qt-install-noninteractive.qs

    - name: Setup environment variables
      run: |
        echo "$QT_INSTALL_DIR/$QT_VERSION/gcc_64/bin" >> $GITHUB_PATH
        echo "$QT_INSTALL_DIR/$QT_VERSION/gcc_64/lib/cmake" >> $GITHUB_PATH
        export Qt6_DIR=$QT_INSTALL_DIR/$QT_VERSION/gcc_64/lib/cmake/Qt6

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=$QT_INSTALL_DIR/$QT_VERSION/gcc_64/lib/cmake/Qt6

    - name: Build project
      run: cmake --build build --config Release -- -j$(nproc)
