name: Qt6 C++ Build with LinguistTools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QT_INSTALL_DIR: ${{ runner.temp }}/Qt6
      QT_VERSION: "6.6.0"
      QT_COMPONENTS: "qtbase,qttools,linguisttools"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          perl \
          libxkbcommon-x11-0 \
          libxcb-xinerama0 \
          libxcb-xinput0 \
          libxcb-xfixes0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libxcb-shm0 \
          libxcb-sync1 \
          libx11-xcb1 \
          libglu1-mesa \
          build-essential \
          cmake \
          ninja-build

    - name: Download Qt installer
      run: |
        wget https://download.qt.io/official_releases/qt/${{ env.QT_VERSION }}/${{ env.QT_VERSION }}/qt-opensource-linux-x64-${{ env.QT_VERSION }}.run -O qt-installer.run
        chmod +x qt-installer.run

    - name: Install Qt non-interactively
      run: |
        sudo QT_INSTALL_DIR=${{ env.QT_INSTALL_DIR }} QT_COMPONENT=${{ env.QT_COMPONENTS }} ./qt-installer.run --script qt-install-noninteractive.qs

    - name: Add Qt binaries to PATH
      run: echo "${{ env.QT_INSTALL_DIR }}/6.6.0/gcc_64/bin" >> $GITHUB_PATH

    - name: Run lupdate (generate/update .ts files)
      run: |
        mkdir -p translations
        lupdate . -recursive -ts translations/*.ts || true

    - name: Run lrelease (generate .qm files)
      run: |
        for tsfile in translations/*.ts; do
          lrelease "$tsfile" -qm "${tsfile%.ts}.qm"
        done

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=${{ env.QT_INSTALL_DIR }} -DCMAKE_BUILD_TYPE=Release -G Ninja

    - name: Build project
      run: |
        cd build
        ninja
