name: Build Qt6 C++ Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install aqtinstall
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install aqtinstall

    - name: Install Qt6
      run: |
        python3 -m aqt list-qt linux desktop  # 查看可用版本
        python3 -m aqt install-qt linux desktop 6.6.0 linux-g++-64 \
          --modules qtbase qttools linguist \
          --outputdir $HOME/Qt \
          --autodesktop
        echo "Qt installed in $HOME/Qt/6.6.0/gcc_64"

    - name: Set Qt environment
      run: |
        export PATH=$HOME/Qt/6.6.0/gcc_64/bin:$PATH
        export CMAKE_PREFIX_PATH=$HOME/Qt/6.6.0/gcc_64/lib/cmake
        echo "PATH=$HOME/Qt/6.6.0/gcc_64/bin:$PATH" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$HOME/Qt/6.6.0/gcc_64/lib/cmake" >> $GITHUB_ENV

    - name: Generate .qm translation files
      run: |
        lupdate . -recursive -ts translations/myapp.ts
        lrelease translations/myapp.ts -qm translations/myapp.qm

    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: |
        cmake --build build --config Release
