name: Build Qt C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout 代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ 安装构建工具和依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git \
          qt6-base-dev qt6-declarative-dev qt6-linguist-tools \
          qt6-tools-dev qt6-tools-dev-tools \
          qt6-multimedia-dev qt6-svg-dev \
          qt6-wayland-dev qt6-x11extras-dev

    # 3️⃣ 设置 Qt6 环境变量
    - name: Set Qt6 environment variables
      run: |
        echo "Qt6_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV

    # 4️⃣ 创建构建目录并运行 CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=$Qt6_DIR

    # 5️⃣ 编译项目
    - name: Build project
      run: cmake --build build -- -j$(nproc)

    # 6️⃣ 可选：运行测试
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    # 7️⃣ 可选：上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: qt-build
        path: build/
