name: Build Qt C++ Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ 安装依赖工具
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git qt6-base-dev

    # 3️⃣ 配置 Qt 环境变量
    - name: Set Qt6 environment variables
      run: |
        echo "Qt6_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV
        # 如果你的 Qt 安装在其他路径，请修改上面路径

    # 4️⃣ 创建构建目录并运行 CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=$Qt6_DIR

    # 5️⃣ 构建项目
    - name: Build project
      run: cmake --build build -- -j$(nproc)

    # 6️⃣ （可选）运行测试
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
