name: Build Qt C++ Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 安装依赖工具
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgl1-mesa-dev

    # 使用 qt-actions/setup-qt 安装 Qt6
    - name: Setup Qt6
      uses: qt-actions/setup-qt@v3
      with:
        version: '6.6.0'
        arch: 'gcc_64'
        modules: 'qtbase,qttools,linguisttools' # 包含 LinguistTools
        host: 'linux'

    # 查看 Qt 版本
    - name: Check Qt version
      run: |
        qmake --version
        lupdate --version
        lrelease --version

    # 更新翻译文件并生成 .qm
    - name: Update translations
      run: |
        lupdate . -recursive -ts translations/app.ts
        lrelease translations/app.ts -qm translations/app.qm

    # 配置和构建
    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$HOME/Qt/6.6.0/gcc_64 -DCMAKE_BUILD_TYPE=Release
        cmake --build . --parallel

    # 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-qt-app
        path: build/
